require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Api::V1::UsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Usuario',
      email: 'another_user@mail.com',
      password: '123123123',
      password_confirmation: '123123123' }
  }

  let(:invalid_attributes) {
    { name: 'Usuario',
      email: '',
      password: '',
      password_confirmation: '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:auth_token) {
    User.create!(email: 'user@mail.com', password: '123123123', password_confirmation: '123123123' )
    AuthenticateUser.call('user@mail.com', '123123123').result
  }

  describe "GET #index" do
    it "returns a success response" do
      user = User.create! valid_attributes
      request.headers.merge!({'Authorization': auth_token, 'Content-Type': 'application/json'})
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      user = User.create! valid_attributes
      request.headers.merge!({'Authorization': auth_token, 'Content-Type': 'application/json'})
      get :show, params: {id: user.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new User" do
        request.headers.merge!({'Authorization': auth_token, 'Content-Type': 'application/json'})
        expect {
          post :create, params: {user: valid_attributes}, session: valid_session
        }.to change(User, :count).by(1)
      end

      it "renders a JSON response with the new user" do
        request.headers.merge!({'Authorization': auth_token, 'Content-Type': 'application/json'})
        post :create, params: {user: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.content_type).to include('application/json')
        expect(response.parsed_body['data']['id']).to eq(api_v1_user_url(User.find(response.parsed_body['data']['id'])).split('/').last)
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new user" do
        request.headers.merge!({'Authorization': auth_token, 'Content-Type': 'application/json'})
        post :create, params: {user: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { name: 'Usuario2',
          email: 'another_user2@mail.com',
          password: '123123123',
          password_confirmation: '123123123' }
      }

      it "updates the requested user" do
        request.headers.merge!({'Authorization': auth_token, 'Content-Type': 'application/json'})
        user = User.create! valid_attributes
        put :update, params: {id: user.to_param, user: new_attributes}, session: valid_session
        user.reload
        expect(user.name).to eq(new_attributes[:name])
        expect(user.email).to eq(new_attributes[:email])
      end

      it "renders a JSON response with the user" do
        request.headers.merge!({'Authorization': auth_token, 'Content-Type': 'application/json'})
        user = User.create! valid_attributes

        put :update, params: {id: user.to_param, user: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to include('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the user" do
        request.headers.merge!({'Authorization': auth_token, 'Content-Type': 'application/json'})
        user = User.create! valid_attributes

        put :update, params: {id: user.to_param, user: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested user" do
      request.headers.merge!({'Authorization': auth_token, 'Content-Type': 'application/json'})
      user = User.create! valid_attributes
      expect {
        delete :destroy, params: {id: user.to_param}, session: valid_session
      }.to change(User, :count).by(-1)
    end
  end

end
